/**
 * @file smooth_mesh_kernel.cpp
 * @brief Implementation of smooth mesh generation kernel
 */

#include <voxel/smooth_mesh_kernel.h>
#include <voxel/mesh_optimizer.h>

namespace jupiter {
namespace voxel {

// ============================================================================
// SmoothMeshKernel Implementation
// ============================================================================

SmoothMeshKernel::SmoothMeshKernel() {
    // Set default configuration
    defaultConfig_.mode = MeshMode::Smooth;
    defaultConfig_.lod = LODLevel::Full;
    defaultConfig_.greedyMeshing = false;
    defaultConfig_.ambientOcclusion = true;
    defaultConfig_.generateTransitions = true;
    defaultConfig_.isoLevel = 0.0f;
}

void SmoothMeshKernel::execute(const SmoothMeshInput& input, SmoothMeshBuffer& output) {
    if (!input.chunk) return;
    
    output.clear();
    
    // Configure meshers
    mcMesher_.setIsoLevel(input.config.isoLevel);
    mcMesher_.setLODLevel(input.config.lod);
    tvMesher_.setIsoLevel(input.config.isoLevel);
    
    // Generate regular cells (including boundaries - Marching Cubes handles neighbor sampling)
    const ChunkColumns* neighbors[6];
    for (int i = 0; i < 6; ++i) {
        neighbors[i] = input.neighbors[i];
    }
    generateRegularCells(*input.chunk, neighbors, input.coord, input.config, output);
    
    // Generate transition cells ONLY for actual LOD transitions
    // For same-LOD boundaries, Marching Cubes handles it seamlessly via neighbor sampling
    // (matching stb_voxel_render and godot_voxel approach)
    if (input.config.generateTransitions) {
        const FaceDirection faces[6] = {
            FACE_POS_X, FACE_NEG_X,
            FACE_POS_Y, FACE_NEG_Y,
            FACE_POS_Z, FACE_NEG_Z
        };
        
        for (int i = 0; i < 6; ++i) {
            // ONLY use Transvoxel for actual LOD transitions
            if (input.neighbors[i] && needsTransition(input.config.lod, input.neighborLODs[i])) {
                // Determine which chunk is high-res and which is low-res
                if (static_cast<int>(input.config.lod) < static_cast<int>(input.neighborLODs[i])) {
                    // This chunk is higher resolution than neighbor - generate transition
                    generateTransitionCells(*input.chunk, *input.neighbors[i], faces[i], input.coord, output);
                    output.hasTransitions = true;
                } else if (static_cast<int>(input.config.lod) > static_cast<int>(input.neighborLODs[i])) {
                    // Neighbor is higher resolution - transition will be generated by neighbor
                    // Skip here (neighbor will handle it)
                }
            }
            // For same-LOD boundaries, Marching Cubes handles it via neighbor sampling
        }
    }
    
    // Store chunk info
    output.chunkX = input.coord.x;
    output.chunkY = input.coord.y;
    output.chunkZ = input.coord.z;
    output.lodLevel = static_cast<uint8_t>(input.config.lod);
    
    // Apply mesh optimizations if we have geometry
    if (!output.empty()) {
        MeshOptConfig optConfig;
        optConfig.optimizeVertexCache = true;
        optConfig.optimizeVertexFetch = true;
        MeshOptimizer::optimize(output, optConfig);
    }
}

void SmoothMeshKernel::execute(const ChunkColumns& chunk,
                                const ChunkColumns* neighbors[6],
                                const ChunkCoord& coord,
                                const MeshConfig& config,
                                SmoothMeshBuffer& output) {
    output.clear();
    
    // Configure meshers
    mcMesher_.setIsoLevel(config.isoLevel);
    mcMesher_.setLODLevel(config.lod);
    tvMesher_.setIsoLevel(config.isoLevel);
    
    // Generate regular cells
    generateRegularCells(chunk, neighbors, coord, config, output);
    
    // Generate transition cells if needed
    if (config.generateTransitions) {
        // Check each face for LOD mismatch
        const FaceDirection faces[6] = {
            FACE_POS_X, FACE_NEG_X,
            FACE_POS_Y, FACE_NEG_Y,
            FACE_POS_Z, FACE_NEG_Z
        };
        
        // Note: This version doesn't have access to neighborLODs
        // The caller should use the SmoothMeshInput version instead
        // For now, skip transitions if we don't have neighbor LOD info
    }
    
    // Store chunk info
    output.chunkX = coord.x;
    output.chunkY = coord.y;
    output.chunkZ = coord.z;
    output.lodLevel = static_cast<uint8_t>(config.lod);
    
    // Apply mesh optimizations if we have geometry
    if (!output.empty()) {
        MeshOptConfig optConfig;
        optConfig.optimizeVertexCache = true;
        optConfig.optimizeVertexFetch = true;
        MeshOptimizer::optimize(output, optConfig);
    }
}

void SmoothMeshKernel::generateRegularCells(const ChunkColumns& chunk,
                                             const ChunkColumns* neighbors[6],
                                             const ChunkCoord& coord,
                                             const MeshConfig& config,
                                             SmoothMeshBuffer& output) {
    // Use Marching Cubes for regular cells
    mcMesher_.process(chunk, neighbors, coord, output);
}

void SmoothMeshKernel::generateTransitionCells(const ChunkColumns& highResChunk,
                                                const ChunkColumns& lowResChunk,
                                                FaceDirection face,
                                                const ChunkCoord& coord,
                                                SmoothMeshBuffer& output) {
    // Use Transvoxel for transition cells
    tvMesher_.processTransition(highResChunk, lowResChunk, face, coord, output);
}

bool SmoothMeshKernel::needsTransition(LODLevel chunkLOD, LODLevel neighborLOD) const {
    // Transition needed if LOD levels differ by 1
    int chunkLevel = static_cast<int>(chunkLOD);
    int neighborLevel = static_cast<int>(neighborLOD);
    
    return std::abs(chunkLevel - neighborLevel) == 1;
}

// ============================================================================
// Kernel Registration
// ============================================================================

// Static kernel for use with kernel system
static VoxelStatus smoothMeshKernelExec(const VoxelExecBatch* input,
                                         VoxelExecBatch* output,
                                         const VoxelKernelContext* ctx) {
    // This is a placeholder for kernel-style execution
    // In practice, SmoothMeshKernel::execute would be called directly
    // with proper typing
    (void)input;
    (void)output;
    (void)ctx;
    return VoxelStatus::Ok;
}

void registerSmoothMeshKernel(VoxelKernelRegistry& registry) {
    VoxelKernel kernel;
    kernel.name = "smooth_mesh";
    kernel.exec = smoothMeshKernelExec;
    kernel.inputColumns = VoxelColumnId::Blocks;   // Blocks + Density
    kernel.outputColumns = VoxelColumnId::MeshBuffer;  // Mesh output
    kernel.mode = VoxelKernelMode::ReadWrite;
    kernel.preferredBatchSize = 1;
    
    registry.registerKernel(kernel);
}

} // namespace voxel
} // namespace jupiter

